{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from starlette.applications import Starlette\n",
    "from starlette.websockets import WebSocketDisconnect\n",
    "import uvicorn, asyncio, json\n",
    "import nest_asyncio\n",
    "nest_asyncio.apply()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "code_folding": [
     5,
     16,
     45
    ]
   },
   "outputs": [],
   "source": [
    "state = {'web_client': False, 'python_client': False}\n",
    "websocket_dict = {}\n",
    "\n",
    "app = Starlette()\n",
    "\n",
    "async def close_client(websocket, msg):\n",
    "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
    "    await websocket.close()\n",
    "\n",
    "async def send_python_status(websocket=None, status=None):\n",
    "    if websocket is None:\n",
    "        if state['web_client']: websocket = websocket_dict['web_client']\n",
    "        else: return\n",
    "    if status is None: status = 'Online' if state['python_client'] else 'Offline'\n",
    "    await websocket.send_json({'event': 'pythonClientStatus', 'msg': status})\n",
    "\n",
    "async def handle_web_client(websocket):\n",
    "    while True:\n",
    "        try:\n",
    "            msg = await websocket.receive_json()\n",
    "            if msg['event'] == 'getPythonClientStatus':\n",
    "                await send_python_status(websocket)\n",
    "            else:\n",
    "                print(f'Invalid event: ({msg[\"event\"]!r}).')\n",
    "        except json.JSONDecodeError: print('Invalid JSON')\n",
    "        except WebSocketDisconnect: break\n",
    "        \n",
    "async def handle_python_client(websocket):\n",
    "    await send_python_status()\n",
    "    while True:\n",
    "        try:\n",
    "            msg = await websocket.receive_json()\n",
    "            await websocket_dict['web_client'].send_json(msg)\n",
    "        except json.JSONDecodeError: print('Invalid JSON')\n",
    "        except WebSocketDisconnect:\n",
    "            await send_python_status(status='Offline')\n",
    "            break\n",
    "\n",
    "func_dict = {'web_client': handle_web_client, 'python_client': handle_python_client}\n",
    "\n",
    "@app.websocket_route('/ws')\n",
    "async def websocket_endpoint(websocket):\n",
    "    await websocket.accept()\n",
    "    msg = await websocket.receive_json()\n",
    "    client_type = msg['client']\n",
    "    if client_type not in state:\n",
    "        await close_client(websocket, f'Invalid client_type ({client_type!r})')\n",
    "        return\n",
    "    if state[client_type]:\n",
    "        await close_client(websocket, 'Client already connected')\n",
    "        return\n",
    "    \n",
    "    state[client_type] = True\n",
    "    websocket_dict[client_type] = websocket\n",
    "    await func_dict[client_type](websocket)\n",
    "    \n",
    "    # Close socket\n",
    "    state[client_type] = False\n",
    "    websocket_dict.pop(client_type)\n",
    "    await close_client(websocket, 'Finalized by server')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO: Started server process [21977]\n",
      "INFO: Waiting for application startup.\n",
      "INFO: Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n",
      "INFO: ('127.0.0.1', 60924) - \"WebSocket /ws\" [accepted]\n",
      "INFO: ('127.0.0.1', 60992) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 32830) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 32906) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 32932) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO: ('127.0.0.1', 32944) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 32978) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 33076) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 33210) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO: ('127.0.0.1', 33260) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 33286) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 33304) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n",
      "INFO: ('127.0.0.1', 33322) - \"WebSocket /ws\" [accepted]\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 658, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO: Shutting down\n",
      "ERROR: Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 674, in transfer_data\n",
      "    message = yield from self.read_message()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 742, in read_message\n",
      "    frame = yield from self.read_data_frame(max_size=self.max_size)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 815, in read_data_frame\n",
      "    frame = yield from self.read_frame(max_size)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 884, in read_frame\n",
      "    extensions=self.extensions,\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/framing.py\", line 99, in read\n",
      "    data = yield from reader(2)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/asyncio/streams.py\", line 677, in readexactly\n",
      "    raise IncompleteReadError(incomplete, n)\n",
      "asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 152, in run_asgi\n",
      "    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/applications.py\", line 102, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/middleware/errors.py\", line 143, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/exceptions.py\", line 58, in __call__\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 550, in __call__\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 283, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/routing.py\", line 57, in app\n",
      "    await func(session)\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 60, in websocket_endpoint\n",
      "    await close_client(websocket, 'Finalized by server')\n",
      "  File \"<ipython-input-3-cecadee7fc75>\", line 7, in close_client\n",
      "    await websocket.send_json({'event': 'close', 'msg': msg})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 116, in send_json\n",
      "    await self.send({\"type\": \"websocket.send\", \"text\": text})\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/starlette/websockets.py\", line 68, in send\n",
      "    await self._send(message)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py\", line 210, in asgi_send\n",
      "    await self.send(data)\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 462, in send\n",
      "    yield from self.ensure_open()\n",
      "  File \"/home/renato/anaconda3/envs/ml/lib/python3.7/site-packages/websockets/protocol.py\", line 646, in ensure_open\n",
      "    ) from self.transfer_data_exc\n",
      "websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason\n",
      "INFO: Waiting for application shutdown.\n",
      "INFO: Finished server process [21977]\n"
     ]
    }
   ],
   "source": [
    "uvicorn.run(app, host='0.0.0.0', port=8000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from starlette.websockets import WebSocket"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "WebSocket.sen"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
